-- public.person definição

-- Drop table

-- DROP TABLE public.person;

CREATE TABLE public.person (
   id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
   address varchar(150) NOT NULL,
   first_name varchar(50) NOT NULL,
   gender varchar(10) NOT NULL,
   last_name varchar(50) NOT NULL,
   CONSTRAINT person_pkey PRIMARY KEY (id)
);