CREATE TABLE public.books (
  id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
  author varchar(200),
  launch_date timestamp NOT NULL,
  price decimal(65,2) NOT NULL,
  title varchar(200)
);
