cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://www.erudio.com.br
spring:
  application:
    name: rest-with-spring-boot-and-java-2025
  datasource:
    url: jdbc:postgresql://localhost:5432/erudio_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
logging:
  level:
    root: INFO
#    br.com.erudio: DEBUG
spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true


